### ISSUE TITLE
Extraneous rows of hyphens in tables for DQ

### ISSUE THREAD

**Issue by levimllr** [learn-co-curriculum/fewpjs-discussion-questions-thinking-in-types#1]
Markdown only requires one row of `| --- | --- |` to denote the preceding row as containing table's column headers. The tables in README.md alternate each row of content with `| --- | --- |`, resulting in rows of hyphens.

Let me know if you would like me to fix this and open a PR!

**Comment by sgharms** [comment]
Thanks. Fixed. PRs gladly accepted though if you want to do that instead of an Issue.
